### ISSUE TITLE
raito-front-docker setup front 

### ISSUE THREAD

**Issue by Nassim-dev** [Raito-HETIC/raito#14]
# General

**EPIC**  | Setup
--- | ---
**Type**  | setup

# TODO 
- Git pull prod and dev
- Create ur own branch from dev like : dl-ny-2 or mrk-nt-95
- Le dev’ commence son travail et effectue des commits réguliers à l’aide de la commande : `git commit -m '[nom du composant] - message #[numero du ticket]'`
- Une fois le ticket terminé :
  - push et créer la PR
  - déplacer la pipeline vers Review - PR Open
  - ajouter les bons labels + auto-assignment
  - ajouter les reviewers : le PO responsable (Chloé ou Val') + PM
  - envoyer le lien de sa PR sur le channel #review
- Merger dès que tout est validé

**Comment by nt-95** [comment]
I tried to install react-scripts via docker-compose and a Dockerfile. But the hot-reload feature is not available for Windows systems. So we decided to use React independently of Docker.
